window.__REWIND_SUPABASE_URL      = 'https://efxjxmtjycldvovcbczg.supabase.co';
window.__REWIND_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmeGp4bXRqeWNsZHZvdmNiY3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMTE4MTEsImV4cCI6MjA5MTc4NzgxMX0.82aeJ6UtcHxkifdjhLsaAXwHeAjyzI2iQ4KakHy3zik';
